branch-defaults:
  default:
    environment: Testapp-env
global:
  application_name: testapp
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.9
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: null
  workspace_type: Application